### ISSUE TITLE
problem when using arc

### ISSUE THREAD

**Issue by Zuckonit** [appbaseio/reactivesearch-api#1]
1. github.com/appbaseio-confidential or github.com/appbaseio ?
2. seems arc only validate the username. password can be anything
3. password should be encrypted stored. (maybe bcrypt)

**Comment by siddharthlatest** [comment]
@Zuckonit All good points, we have fixed 1. Making some fundamental architecture changes before we publish again.

We will look into 2. and 3.

**Comment by siddharthlatest** [comment]
Both 2. and 3. are also resolved now.

**Comment by Zuckonit** [comment]
awesome, how about problem 1

**Comment by siddharthlatest** [comment]
@Zuckonit That is resolved as well. Do you still see it?

**Comment by Zuckonit** [comment]
yeah:  https://github.com/appbaseio/arc/search?utf8=%E2%9C%93&q=appbaseio-confidential&type=

**Comment by siddharthlatest** [comment]
Fixed with https://github.com/appbaseio/arc/commit/f224a40416adf0c7c495ba11b3d634f3e528f05f.
