### ISSUE TITLE
License key and docker installation open source

### ISSUE THREAD

**Issue by Blemming** [appbaseio/reactivesearch-api#251]
### What version of `ReactiveSearch API` are you using ?
Latest version
### What issue did you run into?
Started project up with docker compose, getting error
```
msg="[cmd] Unable to read license file open --log: no such file or directory" file=" entry.go:359"
```
### What did you expect to see?
Expected reactive search api to start up
### What did you see instead?
error:
```
msg="[cmd] Unable to read license file open --log: no such file or directory" file=" entry.go:359"
```

There seems to be something missing steps in the docker setup. Where do I get my license key and where do I put it in the docker compose / env file ?

**Comment by tombburnell** [comment]
I'm getting the same thing..

reactivesearch    | time="2022/02/23 13:47:24" level=fatal msg="[cmd] Unable to read license file open --log: no such file or directory" file=" entry.go:359"

I don't have a license key and don't want to pay for it.

**Comment by siddharthlatest** [comment]
Update: Looking into this

**Comment by siddharthlatest** [comment]
This issue is fixed and should be out with the next release.
