### ISSUE TITLE
do we support multi es backend?

### ISSUE THREAD

**Issue by Zuckonit** [appbaseio/reactivesearch-api#4]
do we support multi es backend?

**Comment by siddharthlatest** [comment]
@Zuckonit What is a multi es backend? Multiple hosts? Can you clarify?

**Comment by Zuckonit** [comment]
sure, multiple es cluster endpoint I mean.
for example:

```
es1.com
es2.com
...
```

**Comment by siddharthlatest** [comment]
The assumption is that the `ES_CLUSTER_URL` will point to a single ES host which is load-balanced across one or more nodes.

**Comment by Zuckonit** [comment]
I am not mean multi nodes, I mean multi es cluster url.
(yes, we have cross cluster search, but its only for search)
